from selenium import webdriver
import time
#d=webdriver.Chrome("C:\\Users\\rashmi\\AppData\\Local\\Programs\\Python\\Python35\\Scripts\\chromedriver.exe")
d=webdriver.Chrome()
# d.get("http://localhost/login.do")
# d.implicitly_wait(5)
# d.find_element_by_xpath("//div[@class='download-button ide']").click()
# d.maximize_window()
# d.find_element_by_id("username").send_keys("admin")
# d.find_element_by_name("pwd").send_keys("manager")
# d.find_element_by_xpath("//div[text()='Login ']").click()
# #d.fullscreen_window()
# d.minimize_window()
# print('curent url',d.current_url)
# print('title',d.title)
# time.sleep(5)
# d.forward()
# d.back()
# cookie={'name':'abc','value':'cde','name':'ram','value':'23'}
# d.add_cookie(cookie)
# print(d.get_cookies())
# c=d.get_cookie('abc')
# print(c)
# #d.close()
